"use client";

import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function LandingPage() {
  return (
    <main className="min-h-screen bg-[#0e0e0e] text-[#eaeaea] font-sans">
      <div className="max-w-6xl mx-auto px-6 py-12">
        {/* Header */}
        <header className="flex justify-between items-center mb-12">
          <h1 className="text-2xl font-semibold tracking-tight">
            Prompt<span className="text-[#4f7cff]">Lens</span>
          </h1>

          <div className="flex gap-3">
            <Link
              href="/login"
              className="rounded-md border border-[#2a2a2a] px-4 py-2 text-sm hover:bg-[#1a1a1a] transition"
            >
              Login
            </Link>
            <Link
              href="/signup"
              className="rounded-md bg-[#4f7cff] px-4 py-2 text-sm font-medium text-white hover:opacity-90 transition"
            >
              Sign Up
            </Link>
          </div>
        </header>

        {/* Hero */}
        <section className="mb-14 max-w-3xl">
          <h2 className="text-4xl md:text-5xl font-semibold leading-tight mb-6">
            Compare how different AI models generate images for the same prompt.
          </h2>

          <p className="text-[#b5b5b5] text-lg leading-relaxed">
            PromptLens is a small project where you can try
            the same prompt on different AI models and see how
            the results vary. It helps in observing differences in style, detail, and overall output in a simple side-by-side format.
          </p>
        </section>

        {/* Comparison Preview */}
        <section className="grid md:grid-cols-2 gap-8 mb-16">
          {/* Model A */}
          <div className="rounded-lg bg-[#151515] p-5 border border-[#222]">
            <div className="mb-3 text-sm text-[#9a9a9a]">
              Model A · Gemini 2.5
            </div>

            <img
              src="/rough-mountain-landscape-drawing.jpg"
              alt="Image generated by Model A"
              className="h-64 w-full object-cover rounded-md"
            />

            <p className="mt-4 text-sm text-[#9a9a9a]">
              Prompt: <span className="italic">“Mountain Sketch”</span>
            </p>
          </div>

          {/* Model B */}
          <div className="rounded-lg bg-[#151515] p-5 border border-[#222]">
            <div className="mb-3 text-sm text-[#9a9a9a]">
              Model B · Gemini 3
            </div>

            <img
              src="/snowy-mountain-peak-sunset.jpg"
              alt="Image generated by Model B"
              className="h-64 w-full object-cover rounded-md"
            />

            <p className="mt-4 text-sm text-[#9a9a9a]">
              Prompt: <span className="italic">“Mountain Sketch”</span>
            </p>
          </div>
        </section>

        {/* Value Props */}
        <section className="grid md:grid-cols-3 gap-10 mb-24">
          <div>
            <h3 className="font-medium mb-2">
              Side-by-side comparison
            </h3>
            <p className="text-sm text-[#a0a0a0]">
              View outputs next to each other so it’s easier to notice small visual differences.
            </p>
          </div>

          <div>
            <h3 className="font-medium mb-2">
              Prompt tracking
            </h3>
            <p className="text-sm text-[#a0a0a0]">
              Use the same prompt across models and compare how each one interprets it.
            </p>
          </div>

          <div>
            <h3 className="font-medium mb-2">
              Simple interface
            </h3>
            <p className="text-sm text-[#a0a0a0]">
              Designed to keep things straightforward without unnecessary features.
            </p>
          </div>
        </section>

        {/* CTA */}
        <section className="text-center">
          <h3 className="text-2xl font-semibold mb-4">
            Try Prompt<span className="text-[#4f7cff]">Lens</span> today
          </h3>
          <p className="text-[#b0b0b0] mb-6">
            Create an account and start comparing model outputs using your own prompts.
          </p>

          <Link
            href="/signup"
            className="inline-block rounded-md bg-[#4f7cff] px-6 py-3 font-medium text-white hover:opacity-90 transition"
          >
            Get Started
          </Link>
        </section>
      </div>
    </main>
  );
}