"use client";

import { Button } from "@/components/ui/button";
import Link from "next/link";

export default function LandingPage() {
  return (
    <main className="min-h-screen bg-background text-foreground font-sans relative">
      {/* Background glow */}
      <div className="fixed top-0 left-1/2 -translate-x-1/2 w-225 h-100 bg-primary/10 blur-[140px] pointer-events-none rounded-full" />

      <div className="max-w-6xl mx-auto px-6 py-12 relative z-10">
        {/* Header */}
        <header className="flex justify-between items-center mb-8">
          <h1 className="text-2xl font-bold tracking-tight text-[#F8F8F8]">
            Analysing <span className="text-[#4757FF] italic">LLMs</span>
          </h1>

          <div className="flex gap-3">
            <Link
              href="/login"
              className="rounded-lg border border-white  px-4 py-2 text-sm text-white hover:bg-white/50 transition"
            >
              Login
            </Link>
            <Link
              href="/signup"
              className="rounded-lg bg-[#4757FF] px-4 py-2 text-sm font-medium text-primary-foreground hover:opacity-90 transition"
            >
              Sign Up
            </Link>
          </div>
        </header>

        {/* Hero */}
        <section className="mb-8 max-w-3xl">
          <h2 className="text-4xl md:text-5xl font-bold leading-tight mb-6 text-[#F8F8F8]">
            Compare Image Outputs from{" "}
            <span className="text-[#4757FF] italic">Multiple AI Models</span>
          </h2>

          <p className="text-muted-foreground text-lg leading-relaxed ">
            Analysing LLMs helps you evaluate how different models respond to
            the same prompt. Compare generated images side-by-side, track prompt
            versions, and make data-driven decisions when building AI products.
          </p>
        </section>

        {/* Comparison Preview */}
        <section className="grid md:grid-cols-2 gap-8 mb-12">
          {/* Model A */}
          <div className="rounded-xl  bg-[#131212] p-5 shadow-sm">
            <div className="mb-3 text-sm font-medium text-muted-foreground">
              Model A · Gemini 2.5
            </div>
            {/* <div className="h-64 rounded-lg bg-muted flex items-center justify-center text-muted-foreground text-sm">
              Image generated by Model A
            </div> */}
            <img
              src="/rough-mountain-landscape-drawing.jpg"
              alt="Image generated by Model A"
              className="h-64 w-full object-cover rounded-lg"
            />
            <p className="mt-4 text-sm text-muted-foreground">
              Prompt: <span className="italic">“Mountain”</span>
            </p>
          </div>

          {/* Model B */}
          <div className="rounded-xl bg-[#131212]  p-5 shadow-sm">
            <div className="mb-3 text-sm font-medium text-muted-foreground">
              Model B · Gemini 3
            </div>
            {/* <div className="h-64 rounded-lg bg-muted flex items-center justify-center text-muted-foreground text-sm">
              Image generated by Model B
            </div> */}
            <img
              src="/snowy-mountain-peak-sunset.jpg"
              alt="Image generated by Model A"
              className="h-64 w-full object-cover rounded-lg"
            />
            <p className="mt-4 text-sm text-muted-foreground">
              Prompt: <span className="italic">“Mountain”</span>
            </p>
          </div>
        </section>

        {/* Value Props */}
        <section className="grid md:grid-cols-3 gap-8 mb-24 text-[#F8F8F8]">
          <div>
            <h3 className="font-semibold mb-2 ">Side-by-Side Evaluation</h3>
            <p className="text-sm text-muted-foreground">
              Instantly see how different models interpret the same prompt.
            </p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">Prompt Versioning</h3>
            <p className="text-sm text-muted-foreground">
              Track prompt changes and understand output differences over time.
            </p>
          </div>

          <div>
            <h3 className="font-semibold mb-2">Built for Builders</h3>
            <p className="text-sm text-muted-foreground">
              Designed for developers, researchers, and AI product teams.
            </p>
          </div>
        </section>

        {/* CTA */}
        <section className="text-center text-[#F8F8F8]">
          <h3 className="text-2xl font-semibold mb-4">
            Start Comparing Models in Minutes
          </h3>
          <p className="text-muted-foreground mb-6">
            Create an account and analyse real model outputs with your own
            prompts.
          </p>
          <Link
            href="/signup"
            className="inline-block rounded-lg bg-[#4757FF] px-6 py-3 font-medium text-primary-foreground hover:opacity-90 transition"
          >
            Get Started
          </Link>
        </section>
      </div>
    </main>
  );
}
